# Generated by Django 4.0.4 on 2022-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank='True', null='True', upload_to='productpics'),
            preserve_default='True',
        ),
    ]
