# Generated by Django 4.0.4 on 2022-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='Image1',
        ),
        migrations.AddField(
            model_name='product',
            name='Image2',
            field=models.ImageField(blank='True', null='True', upload_to='productpics'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='product',
            name='Image3',
            field=models.ImageField(blank='True', null='True', upload_to='productpics'),
            preserve_default='True',
        ),
    ]
