# Generated by Django 4.0.4 on 2022-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_Image',
            field=models.ImageField(blank='True', null='True', upload_to='categorypics'),
            preserve_default='True',
        ),
    ]
